import matplotlib.pyplot as plt

COLORS = {"A": '#39B54A',
          "B": '#8CC63F',
          "C": '#D9E021',
          "D": '#FCEE21',
          "E": '#FBB03B',
          "F": '#F7931E',
          "G": '#F15A24',
          "H": "#CC3333",
          "I": '#4D4D4D'
          }


params = {'legend.fontsize': 'xx-small',
          'axes.labelsize': 'xx-small',
          'axes.titlesize': 'x-small',
          'axes.grid': True,
          'axes.grid.axis': 'y',
          'axes.grid.which': 'major',
          'axes.axisbelow': True,
          'grid.color': 'white',
          'xtick.labelsize': 'x-small',
          'ytick.labelsize': 'x-small',
          'axes.edgecolor': 'white',
          'axes.facecolor': '#EBEBEB',
          'axes.labelcolor': 'black',
          'figure.facecolor': 'white',
          'text.color': 'black',
          'xtick.color': 'black',
          'ytick.color': 'black',
          'legend.edgecolor': 'white',
          'axes.spines.top': False,
          'axes.spines.right': False,
          'axes.spines.left': True,
          'axes.formatter.useoffset': False,
          'lines.marker': 'o',
          'font.family': 'sans-serif',
          'figure.figsize': (6, 6),
          }
